<?php


namespace Database\Seeders;

use App\Models\LocalizationCity;
use Illuminate\Database\Seeder;


class LocalizationCitySeeder extends Seeder
{
    public function run()
    {
        foreach ($this->items() as $item) {
            $user = LocalizationCity::where("id", $item["id"])->first();

            if (!$user) {
                LocalizationCity::create([
                    'id' => $item["id"],
                    'city_name' => $item["city_name"],
                    'plate_no' => $item["plate_no"],
                    'phone_code' => $item["phone_code"],
                    'status' => $item["status"],
                    'country_id' => $item["country_id"],
                    'latitude' => $item["latitude"],
                    'longitude' => $item["longitude"],
                ]);
            }
        }
    }

    private function items()
    {
        return [
            [
                "id" => 1,
                "city_name" => 'Adana',
                "plate_no" => '1',
                "phone_code" => '322',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.0,
                "longitude" => 35.3213,
            ],
            [
                "id" => 2,
                "city_name" => 'Adıyaman',
                "plate_no" => '2',
                "phone_code" => '416',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.7648,
                "longitude" => 38.2786,
            ],
            [
                "id" => 3,
                "city_name" => 'Afyon',
                "plate_no" => '3',
                "phone_code" => '272',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.7507,
                "longitude" => 30.5567,
            ],
            [
                "id" => 4,
                "city_name" => 'Ağrı',
                "plate_no" => '4',
                "phone_code" => '472',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.7191,
                "longitude" => 43.0503,
            ],
            [
                "id" => 68,
                "city_name" => 'Aksaray',
                "plate_no" => '68',
                "phone_code" => '382',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.3687,
                "longitude" => 34.037,
            ],
            [
                "id" => 5,
                "city_name" => 'Amasya',
                "plate_no" => '5',
                "phone_code" => '358',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.6499,
                "longitude" => 35.8353,
            ],
            [
                "id" => 6,
                "city_name" => 'Ankara',
                "plate_no" => '6',
                "phone_code" => '312',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.9208,
                "longitude" => 32.8541,
            ],
            [
                "id" => 7,
                "city_name" => 'Antalya',
                "plate_no" => '7',
                "phone_code" => '242',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 36.8841,
                "longitude" => 30.7056,
            ],
            [
                "id" => 75,
                "city_name" => 'Ardahan',
                "plate_no" => '75',
                "phone_code" => '478',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.1105,
                "longitude" => 42.7022,
            ],
            [
                "id" => 8,
                "city_name" => 'Artvin',
                "plate_no" => '8',
                "phone_code" => '466',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.1828,
                "longitude" => 41.8183,
            ],
            [
                "id" => 9,
                "city_name" => 'Aydın',
                "plate_no" => '9',
                "phone_code" => '256',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.856,
                "longitude" => 27.8416,
            ],
            [
                "id" => 10,
                "city_name" => 'Balıkesir',
                "plate_no" => '10',
                "phone_code" => '266',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.6484,
                "longitude" => 27.8826,
            ],
            [
                "id" => 74,
                "city_name" => 'Bartın',
                "plate_no" => '74',
                "phone_code" => '378',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.5811,
                "longitude" => 32.461,
            ],
            [
                "id" => 72,
                "city_name" => 'Batman',
                "plate_no" => '72',
                "phone_code" => '488',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.8812,
                "longitude" => 41.1351,
            ],
            [
                "id" => 69,
                "city_name" => 'Bayburt',
                "plate_no" => '69',
                "phone_code" => '458',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.2552,
                "longitude" => 40.2249,
            ],
            [
                "id" => 11,
                "city_name" => 'Bilecik',
                "plate_no" => '11',
                "phone_code" => '228',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.0567,
                "longitude" => 30.0665,
            ],
            [
                "id" => 12,
                "city_name" => 'Bingöl',
                "plate_no" => '12',
                "phone_code" => '426',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.0626,
                "longitude" => 40.7696,
            ],
            [
                "id" => 13,
                "city_name" => 'Bitlis',
                "plate_no" => '13',
                "phone_code" => '434',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.3938,
                "longitude" => 42.1232,
            ],
            [
                "id" => 14,
                "city_name" => 'Bolu',
                "plate_no" => '14',
                "phone_code" => '374',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.576,
                "longitude" => 31.5788,
            ],
            [
                "id" => 15,
                "city_name" => 'Burdur',
                "plate_no" => '15',
                "phone_code" => '248',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.4613,
                "longitude" => 30.0665,
            ],
            [
                "id" => 16,
                "city_name" => 'Bursa',
                "plate_no" => '16',
                "phone_code" => '224',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.2669,
                "longitude" => 29.0634,
            ],
            [
                "id" => 17,
                "city_name" => 'Çanakkale',
                "plate_no" => '17',
                "phone_code" => '286',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.1553,
                "longitude" => 26.4142,
            ],
            [
                "id" => 18,
                "city_name" => 'Çankırı',
                "plate_no" => '18',
                "phone_code" => '376',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.6013,
                "longitude" => 33.6134,
            ],
            [
                "id" => 19,
                "city_name" => 'Çorum',
                "plate_no" => '19',
                "phone_code" => '364',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.5506,
                "longitude" => 34.9556,
            ],
            [
                "id" => 20,
                "city_name" => 'Denizli',
                "plate_no" => '20',
                "phone_code" => '258',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.7765,
                "longitude" => 29.0864,
            ],
            [
                "id" => 21,
                "city_name" => 'Diyarbakır',
                "plate_no" => '21',
                "phone_code" => '412',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.9144,
                "longitude" => 40.2306,
            ],
            [
                "id" => 81,
                "city_name" => 'Düzce',
                "plate_no" => '81',
                "phone_code" => '380',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.8438,
                "longitude" => 31.1565,
            ],
            [
                "id" => 22,
                "city_name" => 'Edirne',
                "plate_no" => '22',
                "phone_code" => '284',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.6818,
                "longitude" => 26.5623,
            ],
            [
                "id" => 23,
                "city_name" => 'Elazığ',
                "plate_no" => '23',
                "phone_code" => '424',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.681,
                "longitude" => 39.2264,
            ],
            [
                "id" => 24,
                "city_name" => 'Erzincan',
                "plate_no" => '24',
                "phone_code" => '446',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.75,
                "longitude" => 39.5,
            ],
            [
                "id" => 25,
                "city_name" => 'Erzurum',
                "plate_no" => '25',
                "phone_code" => '442',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.9,
                "longitude" => 41.27,
            ],
            [
                "id" => 26,
                "city_name" => 'Eskişehir',
                "plate_no" => '26',
                "phone_code" => '222',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.7767,
                "longitude" => 30.5206,
            ],
            [
                "id" => 27,
                "city_name" => 'Gaziantep',
                "plate_no" => '27',
                "phone_code" => '342',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.0662,
                "longitude" => 37.3833,
            ],
            [
                "id" => 28,
                "city_name" => 'Giresun',
                "plate_no" => '28',
                "phone_code" => '454',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.9128,
                "longitude" => 38.3895,
            ],
            [
                "id" => 29,
                "city_name" => 'Gümüşhane',
                "plate_no" => '29',
                "phone_code" => '456',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.4386,
                "longitude" => 39.5086,
            ],
            [
                "id" => 30,
                "city_name" => 'Hakkari',
                "plate_no" => '30',
                "phone_code" => '438',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.5833,
                "longitude" => 43.7333,
            ],
            [
                "id" => 31,
                "city_name" => 'Hatay',
                "plate_no" => '31',
                "phone_code" => '326',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 36.4018,
                "longitude" => 36.3498,
            ],
            [
                "id" => 76,
                "city_name" => 'Iğdır',
                "plate_no" => '76',
                "phone_code" => '476',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.888,
                "longitude" => 44.0048,
            ],
            [
                "id" => 32,
                "city_name" => 'Isparta',
                "plate_no" => '32',
                "phone_code" => '246',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.7648,
                "longitude" => 30.5566,
            ],
            [
                "id" => 34,
                "city_name" => 'İstanbul',
                "plate_no" => '34',
                "phone_code" => '212-216',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.0053,
                "longitude" => 28.977,
            ],
            [
                "id" => 35,
                "city_name" => 'İzmir',
                "plate_no" => '35',
                "phone_code" => '232',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.4189,
                "longitude" => 27.1287,
            ],
            [
                "id" => 46,
                "city_name" => 'Kahramanmaraş',
                "plate_no" => '46',
                "phone_code" => '344',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.5858,
                "longitude" => 36.9371,
            ],
            [
                "id" => 78,
                "city_name" => 'Karabük',
                "plate_no" => '78',
                "phone_code" => '370',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.2061,
                "longitude" => 32.6204,
            ],
            [
                "id" => 70,
                "city_name" => 'Karaman',
                "plate_no" => '70',
                "phone_code" => '338',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.1759,
                "longitude" => 33.2287,
            ],
            [
                "id" => 36,
                "city_name" => 'Kars',
                "plate_no" => '36',
                "phone_code" => '474',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.6167,
                "longitude" => 43.1,
            ],
            [
                "id" => 37,
                "city_name" => 'Kastamonu',
                "plate_no" => '37',
                "phone_code" => '366',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.3887,
                "longitude" => 33.7827,
            ],
            [
                "id" => 38,
                "city_name" => 'Kayseri',
                "plate_no" => '38',
                "phone_code" => '352',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.7312,
                "longitude" => 35.4787,
            ],
            [
                "id" => 71,
                "city_name" => 'Kırıkkale',
                "plate_no" => '71',
                "phone_code" => '318',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.8468,
                "longitude" => 33.5153,
            ],
            [
                "id" => 39,
                "city_name" => 'Kırklareli',
                "plate_no" => '39',
                "phone_code" => '288',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.7333,
                "longitude" => 27.2167,
            ],
            [
                "id" => 40,
                "city_name" => 'Kırşehir',
                "plate_no" => '40',
                "phone_code" => '386',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.1425,
                "longitude" => 34.1709,
            ],
            [
                "id" => 79,
                "city_name" => 'Kilis',
                "plate_no" => '79',
                "phone_code" => '348',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 36.7184,
                "longitude" => 37.1212,
            ],
            [
                "id" => 41,
                "city_name" => 'Kocaeli',
                "plate_no" => '41',
                "phone_code" => '262',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.8533,
                "longitude" => 29.8815,
            ],
            [
                "id" => 42,
                "city_name" => 'Konya',
                "plate_no" => '42',
                "phone_code" => '332',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.8667,
                "longitude" => 32.4833,
            ],
            [
                "id" => 43,
                "city_name" => 'Kütahya',
                "plate_no" => '43',
                "phone_code" => '274',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.4167,
                "longitude" => 29.9833,
            ],
            [
                "id" => 44,
                "city_name" => 'Malatya',
                "plate_no" => '44',
                "phone_code" => '422',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.3552,
                "longitude" => 38.3095,
            ],
            [
                "id" => 45,
                "city_name" => 'Manisa',
                "plate_no" => '45',
                "phone_code" => '236',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.6191,
                "longitude" => 27.4289,
            ],
            [
                "id" => 47,
                "city_name" => 'Mardin',
                "plate_no" => '47',
                "phone_code" => '482',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.3212,
                "longitude" => 40.7245,
            ],
            [
                "id" => 33,
                "city_name" => 'Mersin',
                "plate_no" => '33',
                "phone_code" => '324',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 36.8,
                "longitude" => 34.6333,
            ],
            [
                "id" => 48,
                "city_name" => 'Muğla',
                "plate_no" => '48',
                "phone_code" => '252',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.2153,
                "longitude" => 28.3636,
            ],
            [
                "id" => 49,
                "city_name" => 'Muş',
                "plate_no" => '49',
                "phone_code" => '436',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.9462,
                "longitude" => 41.7539,
            ],
            [
                "id" => 50,
                "city_name" => 'Nevşehir',
                "plate_no" => '50',
                "phone_code" => '384',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.6939,
                "longitude" => 34.6857,
            ],
            [
                "id" => 51,
                "city_name" => 'Niğde',
                "plate_no" => '51',
                "phone_code" => '388',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.9667,
                "longitude" => 34.6833,
            ],
            [
                "id" => 52,
                "city_name" => 'Ordu',
                "plate_no" => '52',
                "phone_code" => '452',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.9839,
                "longitude" => 37.8764,
            ],
            [
                "id" => 80,
                "city_name" => 'Osmaniye',
                "plate_no" => '80',
                "phone_code" => '328',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.213,
                "longitude" => 36.1763,
            ],
            [
                "id" => 53,
                "city_name" => 'Rize',
                "plate_no" => '53',
                "phone_code" => '464',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.0201,
                "longitude" => 40.5234,
            ],
            [
                "id" => 54,
                "city_name" => 'Sakarya',
                "plate_no" => '54',
                "phone_code" => '264',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.694,
                "longitude" => 30.4358,
            ],
            [
                "id" => 55,
                "city_name" => 'Samsun',
                "plate_no" => '55',
                "phone_code" => '362',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.2928,
                "longitude" => 36.3313,
            ],
            [
                "id" => 56,
                "city_name" => 'Siirt',
                "plate_no" => '56',
                "phone_code" => '484',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.9333,
                "longitude" => 41.95,
            ],
            [
                "id" => 57,
                "city_name" => 'Sinop',
                "plate_no" => '57',
                "phone_code" => '368',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 42.0231,
                "longitude" => 35.1531,
            ],
            [
                "id" => 58,
                "city_name" => 'Sivas',
                "plate_no" => '58',
                "phone_code" => '346',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.7477,
                "longitude" => 37.0179,
            ],
            [
                "id" => 63,
                "city_name" => 'Şanlıurfa',
                "plate_no" => '63',
                "phone_code" => '414',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.1591,
                "longitude" => 38.7969,
            ],
            [
                "id" => 73,
                "city_name" => 'Şırnak',
                "plate_no" => '73',
                "phone_code" => '486',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 37.4187,
                "longitude" => 42.4918,
            ],
            [
                "id" => 59,
                "city_name" => 'Tekirdağ',
                "plate_no" => '59',
                "phone_code" => '282',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.9833,
                "longitude" => 27.5167,
            ],
            [
                "id" => 60,
                "city_name" => 'Tokat',
                "plate_no" => '60',
                "phone_code" => '356',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.3167,
                "longitude" => 36.55,
            ],
            [
                "id" => 61,
                "city_name" => 'Trabzon',
                "plate_no" => '61',
                "phone_code" => '462',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.0015,
                "longitude" => 39.7178,
            ],
            [
                "id" => 62,
                "city_name" => 'Tunceli',
                "plate_no" => '62',
                "phone_code" => '428',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.3074,
                "longitude" => 39.4388,
            ],
            [
                "id" => 64,
                "city_name" => 'Uşak',
                "plate_no" => '64',
                "phone_code" => '276',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.6823,
                "longitude" => 29.4082,
            ],
            [
                "id" => 65,
                "city_name" => 'Van',
                "plate_no" => '65',
                "phone_code" => '432',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 38.4891,
                "longitude" => 43.4089,
            ],
            [
                "id" => 77,
                "city_name" => 'Yalova',
                "plate_no" => '77',
                "phone_code" => '226',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 40.65,
                "longitude" => 29.2667,
            ],
            [
                "id" => 66,
                "city_name" => 'Yozgat',
                "plate_no" => '66',
                "phone_code" => '354',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 39.8181,
                "longitude" => 34.8147,
            ],
            [
                "id" => 67,
                "city_name" => 'Zonguldak',
                "plate_no" => '67',
                "phone_code" => '372',
                "status" => 1,
                "country_id" => 1,
                "latitude" => 41.4564,
                "longitude" => 31.7987,
            ]
        ];
    }
}
